/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package preguntasTest.vista;

import preguntasTest.clases.Usuario;
import preguntasTest.gestion.DAOProyecto;

/**
 *
 * @author Dam
 */
public class PanelFinal extends javax.swing.JPanel {
    private VentanaPreguntas miVentana;
    private Usuario usuarioActual;
    private Integer numAciertos, numPreguntas;
    /**
     * Creates new form panelFinal
     */
    public PanelFinal(VentanaPreguntas miVentana, Usuario usuario,  Integer numAciertos, Integer numPreguntas) {
        initComponents();
        
        this.miVentana = miVentana;
        this.usuarioActual = usuario;
        this.numAciertos = numAciertos;
        this.numPreguntas = numPreguntas;
        lblAciertos.setText("Número de aciertos: " + numAciertos + " de " + numPreguntas + "\nPorcentaje acertado: " + obtenerPorcentaje() + "%");
    }
    
    public Double obtenerPorcentaje() {
        return Math.round(numAciertos * 10000.0 / numPreguntas) / 100.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAciertos = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(400, 384));
        setMinimumSize(new java.awt.Dimension(400, 384));
        setPreferredSize(new java.awt.Dimension(400, 384));

        lblAciertos.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblAciertos.setText("Número de aciertos: ");
        lblAciertos.setName("lblAciertos"); // NOI18N

        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setName("btnVolver"); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblAciertos)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(lblAciertos)
                .addGap(106, 106, 106)
                .addComponent(btnVolver)
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PanelInicio panel = new PanelInicio(miVentana);
        
        miVentana.cambiarPanel(panel);
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblAciertos;
    // End of variables declaration//GEN-END:variables
}
