package preguntasTest.vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import preguntasTest.clases.Usuario;
import preguntasTest.gestion.DAOProyecto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dam
 */
public class VentanaPreguntas extends javax.swing.JFrame {
    protected JPanel panelActivo;
    protected Usuario usuarioActual;
    ArrayList<Usuario> usuarios;
    /**
     * Creates new form VentanaPreguntasTest
     */
    public VentanaPreguntas() {
        initComponents();
        
        PanelInicio panel = new PanelInicio(this);
        
        this.setSize(500, 500);
        
        panelActivo = panel;
        this.getContentPane().add(panelActivo);
        panelActivo.setSize(this.getSize());
        panelActivo.setVisible(true);
        
        usuarioActual = null;
    }
    
    public Usuario obtenerUsuario() {
        return usuarioActual;
    }
    
    protected void cambiarUsuario(JMenuItem usuario) {
        for (int i = 0; i < menuUsuarios.getItemCount(); i++) {
            if (menuUsuarios.getItem(i) == usuario) {
                usuarioActual = usuarios.get(i);
                menuUsuarios.setText(usuario.getText());
            }
        }
    }  
    
    public void cambiarPanel(JPanel panel){
        panelActivo.setVisible(false);
        this.getContentPane().remove(panelActivo);
        panelActivo = panel;
        this.getContentPane().add(panelActivo);
        panelActivo.setSize(this.getSize());
        panelActivo.setVisible(true);
        
        if (panel instanceof PanelInicio) {
            menuUsuarios.setEnabled(true);
        }
        else {
            menuUsuarios.setEnabled(false);
        }
        
        panelActivo.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarraArriba = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuUsuarios.setText("Usuarios");
        menuBarraArriba.add(menuUsuarios);

        setJMenuBar(menuBarraArriba);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        usuarios = DAOProyecto.getInstance().obtenerUsuarios();
        
        for (int i = 0; i < usuarios.size(); i++) {
            menuUsuarios.add(new JMenuItem(usuarios.get(i).getNombre() + " " + usuarios.get(i).getApellido1() + " " + usuarios.get(i).getApellido2()));
            
            ActionListener accion = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    cambiarUsuario((JMenuItem) e.getSource());
                }
            };
            
            menuUsuarios.getItem(i).addActionListener(accion);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBarraArriba;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
